### ISSUE TITLE
More documentation with configuration

### ISSUE THREAD

**Issue by djcaesar9114** [txstate-etc/ldap-async#1]
I struggle understanding how to connect to my LDAP. I don't user docker for my project so I have to set options directly in the code. How can I use for example this:

```
  const config2= {
    url: 'ldap://127.0.0.1:3004',
    base: 'dc=test,dc=localhost',
    dn: 'cn=root',
    password: 'secret',
  };
```

It's hard to go through the code to check where and how I have to put my config.
Thanks in advance and thanks for your work!

**Comment by wickning1** [comment]
You're right, I didn't document it very well for the non-docker folks. I take care of binding for you so I accept `bindDN` and `bindCredentials` for username and password:
```typescript
import Ldap from 'ldap-async'
export const ldap = new Ldap({
  url: 'ldap://127.0.0.1:3004',
  bindDN: 'cn=root',
  bindCredentials: 'secret'
})
```
There's no base, each operation needs the full path.

**Comment by wickning1** [comment]
It's actually ldapjs that accepts `bindDN` and `bindCredentials`, but it's undocumented. I think I only found them because of typescript. I went ahead and updated the README to include more configuration details and to let people know that I'm wrapping ldapjs.
