### ISSUE TITLE
How to deal with the 'ECONNRESET'

### ISSUE THREAD

**Issue by yanwii** [txstate-etc/ldap-async#2]
In ldapjs, we can handle the error by binding the error event to reconnect the ldap server, just like:

    client.on('error', function(err) {
        console.warn('LDAP connection failed, but fear not, it will reconnect OK', err);
    });

But how to implement it in ldap-async?

**Comment by wickning1** [comment]
We recently got this into production and noticed the same problem. I just pushed out a potential fix. Will keep an eye on it in our own environment to make sure the reconnects are happening appropriately.
