### ISSUE TITLE
How to close the connection to the server

### ISSUE THREAD

**Issue by stuieordie** [txstate-etc/ldap-async#7]
Hi @wickning1  - Probably newby question, but is there a proper way to unbind or close the connection to the LDAP server? I wrote a async function that makes some queries to write data to a file, but the program never exits after it's complete.

Thanks!

**Comment by wickning1** [comment]
Currently there's no way to close down the pool: typically you want to keep it running for the life of the process. For a CLI tool you can call node's `process.exit()` to end your CLI execution and when the process dies that will release all the connections.

In some rare circumstances, you might want to keep your process running after you're completely done using LDAP and you're concerned about leaving open resources. I'll take a look at adding a close() method.

**Comment by wickning1** [comment]
Added and released as 1.3.2.
