### ISSUE TITLE
Allow defining our own logger when initializing the instance

### ISSUE THREAD

**Issue by armpogart** [txstate-etc/ldap-async#9]
The package currently uses `console` to log messages, warnings and errors. The proposal is to add a setter or constructor property to allow defining our own logger to be used when building instance or extending from it.

If you are ok with the proposal, let me know, and I will do the PR.

**Comment by wickning1** [comment]
Yeah that sounds good. It also looks like there's a console.log in there that I would convert to console.info. Thanks!

**Comment by wickning1** [comment]
This is in v2.0.

**Comment by wickning1** [comment]
v2.0 is published.
